enum paquete_estados{
    COMPRAR = 'COMPRAR',
    DEVOLVER = 'DEVOLVER',
    JUNTAR_PLATA = 'JUNTAR_PLATA',
    NO_HAY_DISPONIBLES = 'NO_HAY_DISPONIBLES',
    COMPRANDO= 'COMPRANDO',
    VERIFICAR_COMPRA= 'VERIFICAR_COMPRA',
    VERIFICAR_AGARRE= 'VERIFICAR_AGARRE',
    VERIFICAR_DEVOLUCION = 'VERIFICAR_DEVOLUCION'
}