var MensajeHeader;
(function (MensajeHeader) {
    MensajeHeader["POP_UP_SEABRIO"] = "POPUPSEABRIO";
    MensajeHeader["POP_UP_OPTIONCHANGE"] = "POP_UP_OPTIONCHANGE";
    MensajeHeader["CONTENT_SCRIPT_ASK_EMPIEZO"] = "CONTENT_SCRIPT_ASK_EMPIEZO";
    MensajeHeader["CONTENT_SCRIPT_CAMBIO_PKT"] = "CONTENT_SCRIPT_CAMBIO_PKT";
    MensajeHeader["DEBUGUEAR"] = "DEBUGUEAR";
    MensajeHeader["CONTENT_SCRIPT_PKT_COMPRADO"] = "CONTENT_SCRIPT_PKT_COMPRADO";
    MensajeHeader["CAMBIO_ORO"] = "CAMBIO_ORO";
    MensajeHeader["ACTUALIZAR"] = "ACTUALIZAR";
    //NO_HAY_COMIDA= "NO_HAY_COMIDA",
    //HAY_COMIDA= "HAY_COMIDA",
    MensajeHeader["ACTUALIZAR_EXPEDICION"] = "ACTUALIZAR_EXPEDICION";
    MensajeHeader["LOG_IN"] = "LOG_IN";
    MensajeHeader["ACTIVAR_AK"] = "ACTIVAR_AK";
    MensajeHeader["RESPUESTA"] = "RESPUESTA";
    //ANALIZAR_SUBASTA = 'ANALIZAR_SUBASTA',
    //RESULTADO_SUBASTA = 'RESULTADO_SUBASTA',
    MensajeHeader["CAMBIO_INTENTO_PAQUETES"] = "CAMBIO_INTENTO_PAQUETES";
    MensajeHeader["ANALIZAR_ARENA"] = "ANALIZAR_ARENA";
    MensajeHeader["ANALIZAR_TURMA"] = "ANALIZAR_TURMA";
    MensajeHeader["ANALISIS_INICIAL_MANDADO"] = "ANALISIS_INICIAL_MANDADO";
    MensajeHeader["STOP"] = "STOP";
    MensajeHeader["AUTOOFFER"] = "AUTOOFFER";
    MensajeHeader["LINK_SUBASTA"] = "LINK_SUBASTA";
    MensajeHeader["IR_SUBASTA_ITEM"] = "IR_SUBASTA_ITEM";
    MensajeHeader["ITEMS_ANALIZER"] = "ITEMS_ANALIZER";
    MensajeHeader["ACTUALIZAR_OROPKTS"] = "ACTUALIZAR_OROPKTS";
})(MensajeHeader || (MensajeHeader = {}));
